Facharbeit/lagerappalt/config/routes.rb
Rails.application.routes.draw do
  
  resources :session
  

  get 'signup' => 'users#new'
  resources :users
  root 'customers#index'

    resources :customers do
    	resources :cars do
        resources :tires
      end
    end
	


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Facharbeit/lagerappalt/app/models/customer.rb
class Customer < ApplicationRecord
	has_many :cars

	validates :email, presence: true, format: { with: /(\S+)@(\S+)/ }, uniqueness: { case_sensitive: false} #missachtet die gross oder kleinschreibung der email adresse

end

Facharbeit/lagerappalt/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_customer
  # GET /cars
  # GET /cars.json
  def index
    @cars = @customer.cars
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    
  end

  # GET /cars/new
  def new
    @car = @customer.cars.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = @customer.cars.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to customer_cars_path(@customer.id, @car.id), notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to customer_car_path(@customer.id, @car.id), notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to customer_cars_path(@customer.id), notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:vehicle, :registration, :customer_id)
    end

    def set_customer
      @customer = Customer.find(params[:customer_id])
    end
end

Facharbeit/lagerappalt/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
 
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    
  end
  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:dear, :firstname, :lastname, :street, :city, :plz, :tel, :email, :privacypolicy)
    end
end

Facharbeit/lagerappalt/app/controllers/tires_controller.rb
class TiresController < ApplicationController
  before_action :set_tire, only: [:show, :edit, :update, :destroy]
  before_action :set_customer
  before_action :set_car
  # GET /tires
  # GET /tires.json
  def index
    @tires = @car.tires
  end

  # GET /tires/1
  # GET /tires/1.json
  def show
  end

  # GET /tires/new
  def new
    @tire = @car.tires.new
  end

  # GET /tires/1/edit
  def edit
  end

  # POST /tires
  # POST /tires.json
  def create
    @tire = @car.tires.new(tire_params)
   
    respond_to do |format|
      if @tire.save
         
        format.html { redirect_to customer_car_tires_path(@customer.id, @car.id), notice: 'Tire was successfully created.' }
        format.json { render :show, status: :created, location: @tire }
      else
        format.html { render :new }
        format.json { render json: @tire.errors, status: :unprocessable_entity }
      
    end
  end
end
  # PATCH/PUT /tires/1
  # PATCH/PUT /tires/1.json
  def update
    respond_to do |format|
      if @tire.update(tire_params)
        format.html { redirect_to customer_car_tire_path(@customer.id, @car.id, @tire.id), notice: 'Tire was successfully updated.' }
        format.json { render :show, status: :ok, location: @tire }
      else
        format.html { render :edit }
        format.json { render json: @tire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tires/1
  # DELETE /tires/1.json
  def destroy
    @tire.destroy
    respond_to do |format|
      format.html { redirect_to customer_car_tires_path(@customer.id, @car.id), notice: 'Tire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tire
     #@tire = @car.tire.find(params[:id])
     @tire = Tire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tire_params
      params.require(:tire).permit(:producer, :tiresize, :dotweek, :dotyear, :storage1, :rack, :case, :car_id)
    end

    def set_customer
     @customer = Customer.find(params[:customer_id])
    end

    def set_car
      @car = @customer.cars.find(params[:car_id])
    end
end

Facharbeit/lagerappalt/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Neuer Benutzer wurde angelegt.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Benutzerdaten wurden geändert.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Benutzer wurde gelöscht!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:loginname, :admin, :password, :password_confirmation)
    end
end

Facharbeit/lagerappalt/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', customer_car_path %> |
<%= link_to 'Back', customer_cars_path %>

Facharbeit/lagerappalt/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>KFZ <%= @customer.lastname %></h1>

<table>
  <thead>
    <tr>
      <th><div class="col-md-8">Fahrzeug</div></th>
      <th><div class="col-md-8">Kennzeichen</div></th>
      <th><div class="col-md-8">Kunde</div></th>
      <th><div class="col-md-8">Anzeigen</div></th>
      <th><div class="col-md-8">Reifen anzeigen/hinzufügen</div></th>
      <th><div class="col-md-8">Ändern</div></th>
      <th><div class="col-md-8">Löschen</div></th>

      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td align="center"><%= car.vehicle %></td>
        <td align="center"><%= car.registration %></td>
        <td align="center"><%= car.customer.firstname %> <%= car.customer.lastname %></td>
        <td align="center"><%= link_to 'Fahrzeug anzeigen', customer_car_path(@customer.id, car) %></td>
        <td align="center"><%= link_to 'Reifen', customer_car_tires_path(@customer.id, car) %></td>
        <td align="center"><%= link_to 'Ändern', edit_customer_car_path(@customer.id, car) %></td>
        <td align="center"><%= link_to 'Löschen', customer_car_path(@customer.id, car), method: :delete, data: { confirm: 'Bist du dir sicher das KFZ zu löschen?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neues KFZ anlegen', new_customer_car_path(@customer) %>
</br>
<%= link_to 'Zurück', root_path %>

Facharbeit/lagerappalt/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', customer_cars_path %>
 

Facharbeit/lagerappalt/app/views/customers/edit.html.erb
<h1>Kundendaten ändern</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Anzeigen', @customer, :class => "label label-success" %> |
<%= link_to 'Zurück', customers_path, :class => "label label-info" %>

Facharbeit/lagerappalt/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
 
<h1>Kunden Datei</h1>

<table class="table table-striped">
  <thead>
    <div class="row">
    <tr>
    <% if current_user %>
      <th><div class="col-md-4">Anrede</div></th>
      <th><div class="col-md-4">Vorname</div></th>
      <th><div class="col-md-4">Nachname</div></th>
      <th><div class="col-md-4">Strasse</div></th>
      <th><div class="col-md-4">Stadt</div></th>
      <th><div class="col-md-4">Plz</div></th>
      <th><div class="col-md-4">Tel</div></th>
      <th><div class="col-md-4">Email</div></th>
      <th><div class="col-md-4">Datenschutzerklärung</th></div>
      <th><div class="col-md-4">Anzeigen</th></div>
      <th><div class="col-md-4">Autos</th></div>
    <% if current_user.admin? %>
      <th><div class="col-md-4">Ändern</th></div>
      <th><div class="col-md-4">Löschen</th></div>
    <% end %>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
      <% if current_user %>
        <td><%= customer.dear %></td>
        <td align="left"><%= customer.firstname %></td>
        <td align="left"><%= customer.lastname %></td>
        <td align="left"><%= customer.street %></td>
        <td align="left"><%= customer.city %></td>
        <td align="left"><%= customer.plz %></td>
        <td align="left"><%= customer.tel %></td>
        <td align="left"><%= customer.email %></td>
        <td align="left"><%= db(customer.privacypolicy) %></td>     <!--helper true/Liegt vor/ flase/Liegt nicht vor-->
        <td align="left"><%= link_to 'Kunde anzeigen', customer, :class => "label label-success" %></td>
        <td align="left"><%= link_to 'Autos', customer_cars_path(customer.id), :class => "label label-info" %></td>
      <% if current_user.admin? %>
        <td align="left"><%= link_to 'Ändern', edit_customer_path(customer), :class => "label label-warning" %></td>
        <td align="left"><%= link_to 'Löschen', customer, :class => "label label-danger", method: :delete, data: { confirm: 'Bist du sicher das du den Kunden löschen möchtest?' } %></td>
      <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neuen Kunden anlegen', new_customer_path, :class =>"label label-success" if current_user %>

Facharbeit/lagerappalt/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Karteikarte von <%= @customer.lastname %></h1>

  <table class="table table-striped">
  <thead>
    <div class="row">
    <tr>
      <th><div class="col-md-4">Auto</div></th>
      <th><div class="col-md-4">Kennzeichen</div></th>
      <th><div class="col-md-4">Autodaten ändern</div></th>
      <th><div class="col-md-4">Autodaten löschen</div></th>
      <th><div class="col-md-4">Reifengröße</div></th>
      <th><div class="col-md-4">Lagerort</div></th>
      <th><div class="col-md-4">Regal</div></th>
      <th><div class="col-md-4">Fach</div></th>
      <th><div class="col-md-4">DOT</div></th>
      <th><div class="col-md-4">Reifen hinzufügen</div></th>
      <th><div class="col-md-4">Reifendaten ändern</div></th>
      <th><div class="col-md-4">Reifendaten löschen</div></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @customer.cars.each do |ce| %>

        <td><%= ce.vehicle %></td>
        <td><%= ce.registration %></td>
        <td><%= link_to 'Auto ändern', edit_customer_car_path(@customer, ce), :class => "label label-warning" %></td>
        <td><%= link_to 'Auto löschen', customer_car_path(@customer, ce), method: :delete, data: { confirm: 'Bist du sicher das du das KFZ löschen möchtest?' }, :class => "label label-danger" %></td>
        <td><% ce.tires.each do |ca| %>
          <%= ca.tiresize %></td>
        <td><%= store(ca.storage1) %></td>
        <td><%= ca.rack %></td>
        <td><%= ca.case %></td>
        <td><%= ca.dotweek %> <%= ca.dotyear %></td>
        <td><%= link_to 'Reifen hinzufügen', edit_customer_car_tire_path(@customer, ce, ca), :class => "label label-success" %></td>
        <td><%= link_to 'Reifen ändern', edit_customer_car_tire_path(@customer, ce, ca), :class => "label label-warning" %></td>
        <td><%= link_to 'Reifen löschen', root_path, method: :delete, data: { confirm: 'Bist du sicher das du das KFZ löschen möchtest?' }, :class => "label label-danger" %></td>
        </tr>
 
        <% end %>
        <% end %>
    
  </tbody>
  </table>

<%= link_to 'Kundendaten ändern', edit_customer_path(@customer), :class => "label label-warning" %> |
<%= link_to 'Auto hinzufügen', new_customer_car_path(@customer), :class => "label label-success" %> |
<%= link_to 'Zurück', customer_car_path(@customer), :class => "label label-success" %> | 
 

<!--
<p>
  <strong>Anrede:</strong>
  <%= @customer.dear %>
</p>

<p>
  <strong>Vorname:</strong>
  <%= @customer.firstname %>
</p>

<p>
  <strong>Nachname:</strong>
  <%= @customer.lastname %>
</p>

<p>
  <strong>Strasse:</strong>
  <%= @customer.street %>
</p>

<p>
  <strong>Stadt:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Plz:</strong>
  <%= @customer.plz %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @customer.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Datenschutzerklärung:</strong>
  <%= db(@customer.privacypolicy) %>
</p>
-->

Facharbeit/lagerappalt/app/views/layouts/_nav_bar.html.erb
 <nav class="navbar navbar-inverse">
 <a class="navbar-brand">Lagerverwaltung</a>
  <%= image_tag 'reifen.png', :class => "img-myown", :align => "center" %>
  <div class="container-fluid">
    
    <div class="navbar-header">

      
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Home', root_path %></li>
    <% if current_user %>
      <li class="active"><%= link_to 'Angestellte', users_path %></li>
      <li class="active"><a href="#">Page 332</a></li>
    <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
    <li class="active"><a href="#"><%= current_user.loginname.capitalize %> ist eingeloggt!</a></li>
    <li class="active"><%= link_to 'Log Out', session_path(current_user.id), method: :delete %></li>
    <% else %>
      <li class="active"><%= link_to 'Sign Up', signup_path %></li>
      <li class="active"><%= link_to 'Log In', new_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav> 

Facharbeit/lagerappalt/app/views/tires/edit.html.erb
<h1>Editing Tire</h1>

<%= render 'form', tire: @tire %>

<%= link_to 'Show', customer_car_tires_path %> |
<%= link_to 'Back', customer_car_tires_path %>

Facharbeit/lagerappalt/app/views/tires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reifen Kunde <%= @customer.lastname %> <%= @car.registration %></h1>

<table>
  <thead>
    <tr>
      <th><div class="col-md-8">Hersteller</div></th>
      <th><div class="col-md-8">Reifengrösse</div></th>
      <th><div class="col-md-8">Dot Woche</div></th>
      <th><div class="col-md-8">Dot Jahr</div></th>
      <th><div class="col-md-8">Lager </div></th>
     <!-- <th><div class="col-md-8">Storage 2</div></th>-->
      <th><div class="col-md-8">Regal</div></th>
      <th><div class="col-md-8">Fach</div></th>
      <th><div class="col-md-8">Auto</div></th>
      <th><div class="col-md-8">Anzeigen</div></th>
      <th><div class="col-md-8">Bearbeiten</div></th>
      <th><div class="col-md-8">Löschen</div></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tires.each do |tire| %>
      <tr>
        <td align="center"><%= tire.producer %></td>
        <td align="center"><%= tire.tiresize %></td>
        <td align="center"><%= tire.dotweek %></td>
        <td align="center"><%= tire.dotyear %></td>
        <td align="center"><%= store(tire.storage1) %></td>
        <!--<td><%= store(tire.storage1) %></td>-->
        <td align="center"><%= tire.rack %></td>
        <td align="center"><%= tire.case %></td>
        <td align="center"><%= tire.car.vehicle %></td>
        <td align="center"><%= link_to 'Anzeigen',  customer_car_tire_path(@customer.id, @car.id, tire)  %></td>
        <td align="center"><%= link_to 'Ändern', edit_customer_car_tire_path(@customer.id, @car.id, tire) %></td>
        <td align="center"><%= link_to 'Löschen', customer_car_tire_path(@customer.id, @car.id, tire), method: :delete, data: { confirm: 'Bist du dir sicher die Reifen zu löschen?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neue Reifen anlegen', new_customer_car_tire_path %>
</br>
<%= link_to 'Zurück', customer_cars_path(@customer.id) %>

Facharbeit/lagerappalt/app/views/tires/new.html.erb
<h1>New Tire</h1>

<%= render 'form', tire: @tire %>

<%= link_to 'Back', customer_car_tires_path(@customer.id) %>

Facharbeit/lagerappalt/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= f.label :loginname %></p>
    <%= f.text_field :loginname %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Facharbeit/lagerappalt/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Facharbeit/lagerappalt/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th><div class="col-md-16">Log In Name</div></th>
      <th><div class="col-md-8">Admin</div></th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.loginname %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Facharbeit/lagerappalt/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>