Facharbeit/lagerappMitMail/config/routes.rb
Rails.application.routes.draw do
  
  resources :session
  

  get 'signup' => 'users#new'

  get 'sendmail' => 'customers#sendmail'

  resources :users
  root 'customers#index'

    resources :customers do
      
      resources :cars do
        resources :tires
      end
    end
	


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Facharbeit/lagerappMitMail/app/models/customer.rb
class Customer < ApplicationRecord
	has_many :cars

	validates :email, presence: true, format: { with: /(\S+)@(\S+)/ }, uniqueness: { case_sensitive: false} #missachtet die gross oder kleinschreibung der email adresse

	private
		
	


end

Facharbeit/lagerappMitMail/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
 # before_action :sendmail
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    
  end
  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: 'Kundendaten wurden erfolreich geändert.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def sendmail
     # @customer = Customer.first
     # mail(to: @customer.email, subject: 'Welcome to My Awesome Site')
      @customers = Customer.all
      @customers.each do |customer|
      CustomerMailer.send_mail(customer).deliver_later
      #redirect_to root_path, notice: 'Email is send out.' Läuft noch nicht--------------------------------

    end
      #redirect_to customer_path, notice: 'Email is send out.'
    end    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:dear, :firstname, :lastname, :street, :city, :plz, :tel, :email, :privacypolicy)
    end

   
end

Facharbeit/lagerappMitMail/app/helpers/customers_helper.rb
module CustomersHelper
	def db(privacypolicy)
		if privacypolicy == true
			"Liegt vor"
		else
			"Fehlt!"
		end
	end
end

Facharbeit/lagerappMitMail/app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :anrede %>
    <%= f.text_field :dear %>
  </div>

  <div class="field">
    <%= f.label :vorname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :nachname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :strasse %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :stadt %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :plz %>
    <%= f.text_field :plz %>
  </div>

  <div class="field">
    <%= f.label :tel %>
    <%= f.text_field :tel %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :Datenschutzerklärung %>
    <%= f.check_box :privacypolicy %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Facharbeit/lagerappMitMail/app/views/customers/edit.html.erb
<h1>Kundendaten ändern</h1>

<%= render 'form', customer: @customer %>


<%= link_to 'Zurück', root_path, :class => "label label-info" %>

Facharbeit/lagerappMitMail/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
 
<h1><kbd>Kunden Kartei</kbd></h1>



<table class="table table-striped">
  <thead>
    <div class="row">
    <tr>
    <% if current_user %>
      <th>Anrede</th>
      <th>Vorname</th>
      <th>Nachname</th>
      <th>Strasse</th>
      <th>Stadt</th>
      <th>Plz</th>
      <th>Tel</th>
      <th>E-Mail</th>
      <th>Datenschutzerklärung</th>
      <th>Anzahl&nbspAutos</th>
      <th>Anzeigen</th>
    <% if current_user.admin? %>
      <th>Kundendaten&nbspändern</th>  <!--&nbsp erzeugt ein Leerzeichen ohne umbruch -->
      <th>Löschen</th>
    <% end %>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
      <% if current_user %>
        <td><%= customer.dear %></td>
        <td><%= customer.firstname %></td>
        <td><%= customer.lastname %></td>
        <td><%= customer.street %></td>
        <td><%= customer.city %></td>
        <td><%= customer.plz %></td>
        <td><%= customer.tel %></td>
        <td><%= customer.email %></td>
        <td align="center"><%= db(customer.privacypolicy) %></td>     <!--helper true/Liegt vor/ flase/Liegt nicht vor-->
        <td align="center"><%= customer.cars.count %></td>
        <td><%= link_to 'Kunde anzeigen', customer_path(customer), :class => "label label-info" %></td>
      <% if current_user.admin? %>
        <td align="center"><%= link_to 'Ändern', edit_customer_path(customer), :class => "label label-warning" %></td>
        <td align="center"><%= link_to 'Löschen', customer, :class => "label label-danger", method: :delete, data: { confirm: 'Bist du sicher das du den Kunden löschen möchtest?' } %></td>
      <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neuen Kunden anlegen', new_customer_path, :class =>"label label-success" if current_user %></br></br>

Facharbeit/lagerappMitMail/app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Zurück', customers_path, :class => "label label-info" %>

Facharbeit/lagerappMitMail/app/views/customers/sendmail.html.erb
<h1>Mail senden du WURST</h1>

Facharbeit/lagerappMitMail/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>


<h2><kbd>Karteikarte von <%= @customer.lastname %></kbd></h2>


  <table class="table table-striped">
  <thead>
    <div class="row">
    <tr>
      <th>Auto</th>
      <th>Kennzeichen</th>
      <th>Auto ändern</th>
      <th>Auto löschen</th>
      <th>Reifengröße</th>
      <th>Lagerort</th>
      <th>Regal</th>
      <th>Fach</th>
      <th>DOT</th>
      <th>Reifen hinzufügen oder anzeigen</th>
      <th>Reifen ändern</th>
      <th>Reifen löschen</th>
    </tr>
  </thead>
  <tbody>
    
      <% @customer.cars.each do |ce| %>
      <tr>
        <td><%= ce.vehicle %></td>
        <td><%= ce.registration %></td>
        <td><%= link_to 'Auto ändern', edit_customer_car_path(@customer, ce), :class => "label label-warning" %></td>
        <td><%= link_to 'Auto löschen', customer_car_path(@customer, ce), method: :delete, data: { confirm: 'Bist du sicher das du das KFZ löschen möchtest?' }, :class => "label label-danger" %></td>
        
        <% if ce.tires.present? %>  <!--Wenn sich Daten in der Tabelle tires befinden, anzeigen else colspan 5 und Reifen hinzufügen-->
          <% ce.tires.each do |ca| %>
            <td><%= ca.tiresize %></td>
            <td><%= store(ca.storage1) %></td>
            <td><%= ca.rack %></td>
            <td><%= ca.case %></td>
            <td><%= ca.dotweek %> <%= ca.dotyear %></td>
            <td align="center"><%= link_to 'Lagerort anzeigen', customer_car_tires_path(@customer, ce, ca), :class => "label label-info" %></td>
            <td><%= link_to 'Reifen ändern', edit_customer_car_tire_path(@customer, ce, ca), :class => "label label-warning" %></td>
            <td><%= link_to 'Reifen löschen', customer_car_tire_path(@customer, ce, ca), method: :delete, data: { confirm: 'Bist du sicher das du die Reifen löschen möchtest?' }, :class => "label label-danger" %></td>        
          <% end %>
        <% else %>
            <td colspan='5'>&nbsp;</td> <!--Füllt die 5 leeren Felder der Tbelle tires aus -->
            <td align="center"><%= link_to 'Reifen hinzufügen', new_customer_car_tire_path(@customer, ce), :class => "label label-success" %></td>
            <td colspan='2'>&nbsp;</td>
        <% end %>
      </tr>
      <% end %>
        
    
  </tbody>
  </table>


<%= link_to 'Auto hinzufügen', new_customer_car_path(@customer), :class => "label label-success" %></br></br>
<%= link_to 'Zurück', root_path, :class => "label label-info" %>
 

<!--
<p>
  <strong>Anrede:</strong>
  <%= @customer.dear %>
</p>

<p>
  <strong>Vorname:</strong>
  <%= @customer.firstname %>
</p>

<p>
  <strong>Nachname:</strong>
  <%= @customer.lastname %>
</p>

<p>
  <strong>Strasse:</strong>
  <%= @customer.street %>
</p>

<p>
  <strong>Stadt:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Plz:</strong>
  <%= @customer.plz %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @customer.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Datenschutzerklärung:</strong>
  <%= db(@customer.privacypolicy) %>
</p>
-->