Facharbeit/lagerappMitMail/config/routes.rb
Rails.application.routes.draw do
  
  resources :session
  

  get 'signup' => 'users#new'

  get 'sendmail' => 'customers#sendmail'

  resources :users
  root 'customers#index'

    resources :customers do
      
      resources :cars do
        resources :tires
      end
    end
	


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Facharbeit/lagerappMitMail/app/views/layouts/_nav_bar.html.erb
 <nav class="navbar navbar-inverse">
 <a class="navbar-brand">Lagerverwaltung</a>
  <%= image_tag 'reifen.png', :class => "img-myown", :align => "center" %>
  <div class="container-fluid">
    
    <div class="navbar-header">

      
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Kundenkartei', root_path %></li>
    <% if current_user %>
      <li class="active"><%= link_to 'Mitarbeiter', users_path %></li>
      <li class="active"><%= link_to 'Kundenmail', sendmail_path %></li>
    <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
    <li class="active"><a href="#"><%= current_user.loginname.capitalize %> ist eingeloggt!</a></li>
    <li class="active"><%= link_to 'Log Out', session_path(current_user.id), method: :delete %></li>
    <% else %>
      <li class="active"><%= link_to 'Sign Up', signup_path %></li>
      <li class="active"><%= link_to 'Log In', new_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav> 

Facharbeit/lagerappMitMail/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lagerapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
  <div class="container">
  	<%= render 'layouts/nav_bar' %>
    <%= yield %>
  </div>
  </body>
  
</html>